---
title: "Data Exploration"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
#tidyverse for organizing the data, industry standard for data organization
#make sure you have LaTeX installed to knit to PDF
#if using windows you can install it by running tinytex::install_tinytex() in the console
```



```{r}
#import data
primary <- read_delim('primary.txt', delim = '|', quote="", na="?", col_types = cols(
  worknumber=col_integer(),
  pubDate=col_date(format = "%d %b %Y"),
  summary=col_character(),
  wordCount=col_number(),
  chaptersWritten=col_number(),
  chaptersTotal=col_number(),
  collections=col_number(),
  comments=col_number(),
  kudos=col_number(),
  bookmarks=col_number(),
  hits=col_number(),
  visitedDate=col_date(format = "%d %b %Y"),
  visitCount=col_number()
))


authors <- read_delim('authors.txt', delim = '|', col_types = cols(
  worknumber=col_integer()
))

```


```{r, echo=FALSE}
#view summary of data
summary(primary)
head(primary)
summary(authors)
head(authors)
```
```{r, echo=FALSE}
#find top author by number of works view
topAuthorsWorks <- authors %>%
  group_by(authors) %>%
  summarise(numWorks = n()) %>%
  arrange(desc(numWorks))


#find top author by total visit count
topAuthorsCount <- left_join(authors, primary, by = 'worknumber') %>%
  group_by(authors) %>%
  summarise(numVisits = sum(visitCount)) %>%
  arrange(desc(numVisits))

head(topAuthorsCount, 25)

```
